version: '3.1'
services:
  meu-consumo-postgresql:
    image: postgres:12.3
    volumes:
      - ./docker/dump-postgres:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=meuconsumo
      - POSTGRES_PASSWORD=meuconsumo
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
